default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  socket: /tmp/.s.PGSQL.5432
  database: beaver-development

test:
  <<: *default
  database: beaver-test

production:
  <<: *default
  database: beaver-production
